### PR TITLE
Add microseconds timeout support

### PR DESCRIPTION
**Pull request by rybakit**
This is an alternative to #71 with a slightly refactored `StreamConnection` class and improved tests for timeouts and options.

### CODE REVIEW

**Review by xBazilio — APPROVED** [review]
This works for me. Thank you! Waiting for new tag.

**Comment by rybakit** [comment]
@xBazilio Since these changes break BC, they cannot go into 0.9.1, and before releasing 0.10 I want to add some more incompatible changes. So for now, if you need this feature asap, you can either use dev-master or the exact commit hash.

**Comment by xBazilio** [comment]
> @xBazilio Since these changes break BC, they cannot go into 0.9.1, and before releasing 0.10 I want to add some more incompatible changes. So for now, if you need this feature asap, you can either use dev-master or the exact commit hash.

@rybakit Can you tell approximately when 0.10 will be available?

**Comment by rybakit** [comment]
@xBazilio It depends on how much free time I will actually have, but roughly it will take at least 2 weeks. Btw, there is a Teregram channel about tarantool+php development where you are welcome to ping me if you have any questions: https://t.me/tarantool_php.

**Pull request merged**
